'use client';
import {useEffect,useRef,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Layers3,Activity,Coins,Landmark,Wallet,FlaskConical,ShieldCheck,Plus,Minus} from 'lucide-react';
import {PublicHeader,Footer,whitepaper} from './Public';
import {CapitalObject} from './CapitalObject';
import {vaults} from '@/lib/domain';
const modules=[{name:'Strategy vaults',id:'vaults',icon:Layers3,label:'Define your mandate',text:'Explore six strategy classes. Set an allocation, define its limits, and understand its exposure before taking action.'},{name:'Markets & liquidity',id:'markets',icon:Activity,label:'Understand the market',text:'Bring public market data, paper trading, and liquidity exploration into a connected workspace.'},{name:'Token Studio',id:'tokens',icon:Coins,label:'Create with intention',text:'Configure a fixed-supply asset, review its permissions, and prepare a transparent testnet deployment.'},{name:'Asset credit',id:'credit',icon:Landmark,label:'Know your boundaries',text:'Explore collateral and borrowing in a model that makes its limits and assumptions explicit.'},{name:'Treasury',id:'treasury',icon:Wallet,label:'Give capital a purpose',text:'Define how capital is distributed across reserves, liquidity, infrastructure, and ecosystem priorities.'},{name:'Strategy laboratory',id:'laboratory',icon:FlaskConical,label:'Examine the idea',text:'Adjust a scenario, inspect its calculated results, and understand the model before making an allocation.'}];
const stages=[['Observe','Start with a clear view.','Bring conditions, positions, and available information into view.'],['Evaluate','Turn context into a decision.','Compare the proposed action with the strategy’s objective and limits.'],['Authorize','Your permissions are the checkpoint.','An action must stay inside the authority and boundaries you define.'],['Execute','Move only within the mandate.','Carry out the permitted action through supported infrastructure.'],['Record','Leave a visible record.','Keep the outcome, its source, and its execution state inspectable.'],['Reassess','Keep the context in view.','Review the result and changing conditions before the next decision.']];
export default function Landing(){const [selected,setSelected]=useState(0),[stage,setStage]=useState(0);const cycle=useRef<HTMLElement>(null);
 useEffect(()=>{const root=cycle.current;if(!root||!('IntersectionObserver' in window))return;const rows=root.querySelectorAll('[data-cycle-step]');const observer=new IntersectionObserver(entries=>{const active=entries.filter(e=>e.isIntersecting).sort((a,b)=>b.intersectionRatio-a.intersectionRatio)[0];if(active)setStage(Number((active.target as HTMLElement).dataset.cycleStep));},{rootMargin:'-25% 0px -30% 0px',threshold:[0,.25,.5,.75,1]});rows.forEach(r=>observer.observe(r));return()=>observer.disconnect();},[]);
 return <div className="landing-page"><PublicHeader/><main id="main">
  <section className="landing-hero" aria-labelledby="landing-title"><div className="landing-hero-copy"><div className="landing-kicker"><span className="kicker-rule"/> AUTONOMOUS FINANCE, DEFINED BY YOU</div><h1 id="landing-title"><span className="word-mask"><span>Capital,</span></span><span className="word-mask"><span>in motion.</span></span><span className="word-mask accent"><span>By your rules.</span></span></h1><p>One connected ecosystem for financial strategies.<br className="desktop"/> Build with intent. Move within your limits.</p><div className="landing-actions"><Button asChild className="cta large"><a href="/app">Explore Dynamica</a></Button><a href={whitepaper} target="_blank" rel="noreferrer" className="landing-text-link">Read the whitepaper</a></div><div className="hero-note"><ShieldCheck size={15}/><span>Explore without a wallet. Demo actions never move funds.</span></div></div><CapitalObject/><div className="hero-bottom"><span>PROGRAMMABLE CAPITAL / EXPLICIT CONTROL</span><a href="#ecosystem" className="scroll-label">SCROLL TO EXPLORE<span className="scroll-track"><i/></span></a></div></section>
  <section className="landing-intro landing-section" id="ecosystem"><div className="landing-section-top"><span className="landing-kicker">01 / A CONNECTED ECOSYSTEM</span><span className="section-index">SIX TOOLS. SHARED INTENT.</span></div><div className="landing-intro-heading"><h2>Different possibilities.<br/><span>A common foundation.</span></h2><p>Capital works across markets, strategies, and assets. Dynamica brings these activities into a shared environment—with their boundaries in view.</p></div><div className="ecosystem-browser"><div className="ecosystem-list">{modules.map((m,i)=><div className={'ecosystem-item '+(selected===i?'is-selected':'')} key={m.id}><button aria-expanded={selected===i} aria-controls={'module-'+m.id} onClick={()=>setSelected(i)}><span className="module-number">0{i+1}</span><strong>{m.name}</strong>{selected===i?<Minus size={18}/>:<Plus size={18}/>}</button><div id={'module-'+m.id} className="module-inline" hidden={selected!==i}><p>{m.text}</p><a href={'/app?view='+m.id}>Open {m.name.toLowerCase()}</a></div></div>)}</div><div className="ecosystem-preview" aria-hidden="true"><div className="preview-eyebrow"><span>THE DYNAMICA ECOSYSTEM</span><span>0{selected+1} / 06</span></div><div className="module-glyph" key={selected}>{(()=>{const Icon=modules[selected].icon;return <Icon strokeWidth={.8}/>;})()}</div><div className="preview-copy" key={'copy-'+selected}><span>{modules[selected].label}</span><h3>{modules[selected].name}</h3><div className="module-progress">{modules.map((m,i)=><i key={m.id} className={selected===i?'active':''}/>)}</div></div></div></div></section>
  <section className="landing-cycle landing-section" ref={cycle} aria-labelledby="cycle-title"><div className="cycle-sticky"><span className="landing-kicker">02 / THE DECISION CYCLE</span><h2 id="cycle-title">Intelligence.<br/>With <span>boundaries.</span></h2><p>Autonomy is a sequence of accountable decisions. Every step has a role. Every action has a limit.</p><div className="cycle-dial" aria-hidden="true"><svg viewBox="0 0 220 220"><circle className="dial-track" cx="110" cy="110" r="93"/><circle className="dial-progress" cx="110" cy="110" r="93" strokeDasharray="584.34" strokeDashoffset={584.34*(1-(stage+1)/6)}/></svg><div><span>0{stage+1} / 06</span><strong>{stages[stage][0]}</strong></div></div><a className="landing-text-link" href="/app?view=operators">Explore the operator cycle</a></div><div className="cycle-narrative">{stages.map(([title,heading,text],i)=><article data-cycle-step={i} className={'cycle-chapter '+(stage===i?'is-current':'')+(i===2?' checkpoint':'')} key={title}><div className="chapter-top"><span>0{i+1}</span><span>{title}</span>{i===2&&<ShieldCheck size={18}/>}</div><h3>{heading}</h3><p>{text}</p>{i===2&&<span className="checkpoint-label">THE PERMISSION CHECKPOINT</span>}</article>)}</div></section>
  <section className="landing-strategies landing-section"><div className="landing-section-top"><span className="landing-kicker">03 / STRATEGY BY DESIGN</span><a className="landing-text-link" href="/app?view=vaults">Explore all strategies</a></div><h2>Define the direction.<br/><span>Then define the limits.</span></h2><div className="strategy-catalog">{vaults.map((v,i)=><a className="catalog-row" href={'/app?view=vaults&id='+v.id} key={v.id}><span className="catalog-number">0{i+1}</span><h3>{v.type}</h3><span className="catalog-description">{v.tag}</span><span className="catalog-action">Explore<span className="catalog-cross">+</span></span></a>)}</div><div className="catalog-note"><span className="mode-label">INTERACTIVE DEMOS</span><p>Explore the framework with example capital. Live protocol actions depend on verified integrations.</p></div></section>
  <section className="landing-close landing-section"><div className="close-hairline"/><span className="landing-kicker">THE NEXT MOVE IS YOURS</span><h2>Intent into <span>action.</span></h2><p>Start with a strategy. Keep control of what comes next.</p><div className="landing-actions"><Button asChild className="cta large"><a href="/app">Launch Dynamica</a></Button><a className="landing-text-link" href="/docs">Understand the system</a></div><div className="close-watermark" aria-hidden="true">dynamica.</div></section>
 </main><Footer/></div>;
}
