import {network} from 'hardhat';
import {parseUnits,id} from 'ethers';
const {ethers,networkName}=await network.create();
const chain=await ethers.provider.getNetwork();
if(networkName==='robinhoodTestnet'&&chain.chainId!==46630n)throw Error('Wrong chain ID');
if(![46630n,31337n].includes(chain.chainId))throw Error('MVP deployment permits testnet or local chain only');
const [deployer]=await ethers.getSigners();
const owner=await deployer.getAddress();
const asset=await ethers.deployContract('DynamicaTestAsset');await asset.waitForDeployment();
const factory=await ethers.deployContract('DynamicaVaultFactory');await factory.waitForDeployment();
const assetAddress=await asset.getAddress();
const cap=parseUnits('1000000',18),salt=id('Dynamica MVP vault');
const predicted=await factory.predictVault(assetAddress,cap,owner,salt);
await(await factory.createVault(assetAddress,cap,salt)).wait();
const vault=await ethers.getContractAt('DynamicaStrategyVault',predicted);
if(await vault.owner()!==owner)throw Error('Unexpected vault owner');
console.log(`Network: ${networkName} (${chain.chainId})\nOwner: ${owner}\nFactory: ${await factory.getAddress()}\nReserve: ${await vault.reserve()}`);
console.log(`NEXT_PUBLIC_DYNAMICA_ASSET_ADDRESS=${assetAddress}\nNEXT_PUBLIC_DYNAMICA_VAULT_ADDRESS=${predicted}\nDYNAMICA_VAULT_ADDRESS=${predicted}`);
console.log('No operator is configured. Connect as the owner to review and authorize a policy.');
