import {network} from 'hardhat';
import {strict as assert} from 'node:assert';
import {createPublicClient, createWalletClient, custom, getAddress, parseEventLogs, type Address} from 'viem';
import {foundry} from 'viem/chains';
import {StrategyVaultClient, parseAssetAmount} from '../../packages/sdk/src/index.ts';
import {DynamicaStrategyVaultAbi} from '../../packages/abi/src/contracts.ts';

const connection = await network.create();
const {ethers} = connection;
assert.equal((await ethers.provider.getNetwork()).chainId,31337n,'Local journey only');
const [owner,user,keeper,outsider] = await ethers.getSigners();
const asset = await ethers.deployContract('DynamicaTestAsset'); await asset.waitForDeployment();
const factory = await ethers.deployContract('DynamicaVaultFactory'); await factory.waitForDeployment();
const cap = parseAssetAmount('200',18), amount = parseAssetAmount('100',18);
const assetAddress = await asset.getAddress(), salt = ethers.id('dynamica-sdk-journey-v1');
const address = getAddress(await factory.predictVault(assetAddress,cap,await owner.getAddress(),salt));
await (await factory.createVault(assetAddress,cap,salt)).wait();
const transport = custom({request:({method,params})=>connection.provider.request({method,params})});
const publicClient = createPublicClient({chain:foundry,transport,pollingInterval:10});
const client = async (signer:typeof user, chainId=31337) => new StrategyVaultClient(publicClient,
  createWalletClient({chain:foundry,transport,account:getAddress(await signer.getAddress())}),address,chainId);
const allocator = await client(user), administrator = await client(owner), operator = await client(keeper);
const vault = await ethers.getContractAt('DynamicaStrategyVault',address);
await (await asset.connect(user).getFunction('claim')()).wait();
await assert.rejects((await client(user,46630)).approveExact(amount),/Wrong network/);
await allocator.approveExact(amount);
const depositReceipt = await allocator.deposit(amount,amount);
assert.equal(depositReceipt.status,'success');
assert.equal(await vault.totalAssets(),amount);
assert.equal(await vault.balanceOf(await user.getAddress()),amount);
const state = await allocator.snapshot();
assert.equal(state.mode,'Local');
await administrator.configure({operator:getAddress(await keeper.getAddress()),reserveBps:8000,
  minInterval:60n,windowDuration:3600n,expiresAt:state.timestamp+604800n,maxMove:amount,windowLimit:amount});
const prepared = await operator.prepareExecution();
await assert.rejects((await client(outsider)).execute(prepared));
const receipt = await operator.execute(prepared);
const events = parseEventLogs({abi:DynamicaStrategyVaultAbi,logs:receipt.logs,eventName:'Rebalanced'});
assert.equal(events.length,1);
assert.equal(events[0].args.assets,parseAssetAmount('80',18));
assert.equal(await vault.idleAssets(),parseAssetAmount('20',18));
assert.equal(await vault.totalAssets(),amount);
await connection.provider.request({method:'evm_increaseTime',params:[60]});
await connection.provider.request({method:'evm_mine'});
await assert.rejects(operator.execute(prepared));
assert.equal(await vault.executionCount(),1n);
await administrator.revoke();
await (await vault.setExecutionPaused(true)).wait();
await (await vault.setDepositsPaused(true)).wait();
await allocator.redeem(amount,amount);
assert.equal(await asset.balanceOf(await user.getAddress()),amount);
assert.equal(await vault.totalAssets(),0n);
assert.equal(await vault.totalSupply(),0n);
const reserve = await ethers.getContractAt('DynamicaReserve',await vault.reserve());
assert.equal(await reserve.totalAssets(),0n);
console.log('SDK local journey passed: create → claim → exact approval → deposit → authorize → execute → reject replay → revoke/pause → redeem.');
console.log('Wrong-network and unauthorized-operator requests rejected; receipt event and final asset conservation verified.');
