import {network} from 'hardhat';
import {strict as assert} from 'node:assert';
import {parseUnits,id} from 'ethers';
const {ethers}=await network.create();
assert.equal((await ethers.provider.getNetwork()).chainId,31337n,'Smoke test is local only');
const [owner,user,keeper]=await ethers.getSigners();
const asset=await ethers.deployContract('DynamicaTestAsset');await asset.waitForDeployment();
const factory=await ethers.deployContract('DynamicaVaultFactory');await factory.waitForDeployment();
const assetAddress=await asset.getAddress(),salt=id('integration smoke'),cap=parseUnits('200',18);
const address=await factory.predictVault(assetAddress,cap,await owner.getAddress(),salt);
await(await factory.createVault(assetAddress,cap,salt)).wait();
const vault=await ethers.getContractAt('DynamicaStrategyVault',address);
const account=await user.getAddress();
await(await asset.connect(user).getFunction('claim')()).wait();
await(await asset.connect(user).getFunction('approve')(address,parseUnits('100',18))).wait();
await(await vault.connect(user).getFunction('deposit')(parseUnits('100',18),account)).wait();
const block=await ethers.provider.getBlock('latest');
await(await vault.configurePolicy({operator:await keeper.getAddress(),reserveBps:8000,minInterval:60,
 windowDuration:3600,expiresAt:block!.timestamp+604800,maxMove:parseUnits('100',18),windowLimit:parseUnits('100',18)})).wait();
await(await vault.connect(keeper).getFunction('rebalance')(1,parseUnits('80',18))).wait();
assert.equal(await vault.idleAssets(),parseUnits('20',18));
assert.equal(await vault.totalAssets(),parseUnits('100',18));
await(await vault.revokeOperator()).wait();
await(await vault.connect(user).getFunction('withdraw')(parseUnits('100',18),account,account)).wait();
assert.equal(await asset.balanceOf(account),parseUnits('100',18));
assert.equal(await vault.totalAssets(),0n);
assert.equal(await vault.totalSupply(),0n);
console.log('Factory → claim → approve → deposit → authorize → rebalance → revoke → withdraw passed.');
