import {readFileSync, writeFileSync, mkdirSync} from 'node:fs';
const names = ['DynamicaStrategyVault', 'DynamicaReserve', 'DynamicaVaultFactory', 'DynamicaTestAsset'];
const declarations = ['// Generated by scripts/export-abi.mjs from compiled Hardhat artifacts. Do not edit.'];
for (const name of names) {
  const artifact = JSON.parse(readFileSync(`chain/artifacts/contracts/${name}.sol/${name}.json`, 'utf8'));
  declarations.push(`export const ${name}Abi = ${JSON.stringify(artifact.abi, null, 2)} as const;`);
  if (name === 'DynamicaStrategyVault') {
    const reads = ['asset','decimals','totalAssets','totalSupply','assetCap','depositsPaused','balanceOf','maxWithdraw','idleAssets','policyVersion','windowRemaining','executionPaused','reserve','previewRebalance'];
    writeFileSync('python/vault_read_abi.json', JSON.stringify(artifact.abi.filter(item => reads.includes(item.name)), null, 2) + '\n');
  }
}
mkdirSync('packages/abi/src', {recursive:true});
writeFileSync('packages/abi/src/contracts.ts', declarations.join('\n\n') + '\n');
